// <auto-generated />
using System;
using DMonoStereo.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMonoStereo.Core.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    partial class MusicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DMonoStereo.Core.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CoverImage")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_Albums_ArtistId");

                    b.HasIndex("DateAdded")
                        .HasDatabaseName("IX_Albums_DateAdded");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Albums_Name");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Albums_Year");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateAdded")
                        .HasDatabaseName("IX_Artists_DateAdded");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artists_Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Tracks_AlbumId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tracks_Name");

                    b.HasIndex("TrackNumber")
                        .HasDatabaseName("IX_Tracks_TrackNumber");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Album", b =>
                {
                    b.HasOne("DMonoStereo.Core.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Track", b =>
                {
                    b.HasOne("DMonoStereo.Core.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("DMonoStereo.Core.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
